version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-quiz
    command: sh -c "chmod +x .docker/app.sh && ./.docker/app.sh"
    ports:
      - "3030:3030"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env-docker
    environment:
      - MYSQL_PASSWORD="password"
      - MYSQL_DATABASE="db"
      - MYSQL_USER="user"
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    
volumes:
  my-db: